name: Fetch BaseUtils Binaries
#MAX_RUNTIME: 15 Minutes 45 21 * * * [21:45 (09:45 PM) UTC --> (05H+45M) 03:30 AM NPT ]

on:
  workflow_dispatch:
  schedule:
    - cron: "* * */7 * *"  #Every 7 Days
  # https://crontab.guru
  # https://savvytime.com/converter/utc-to-nepal-kathmandu

env:
  # https://i.redd.it/o6xypg00uac91.png
  USER_AGENT: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/115.0.5790.160 Mobile/15E148 Safari/604.1"
  GITHUB_TOKEN: ${{ secrets.STATIC_BINARIES_RELEASER }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Install CoreUtils
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends bison build-essential ca-certificates flex file jq pkg-config qemu-user-static wget

      - name: Install Addons
        run: |
          set +e
          #eget
          curl -qfsSL "https://zyedidia.github.io/eget.sh" | bash
          sudo mv ./eget* "/usr/local/bin/eget"
          sudo chmod +xwr "/usr/local/bin/eget"
        continue-on-error: true

      - name: Setup Env
        run: |
          # Create Output Dir
          #aarch64_arm64
          mkdir -p "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #armv7_eabihf
          mkdir -p "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf"
          #x86_64
          mkdir -p "$GITHUB_WORKSPACE/main/baseutils/x86_64"

     #Fetch
      - name: Fetch baseutils
        run: |
         #Download
          set -x ; set +e
         #-------------------------#
          #----------#         
          ##coreutils
          eget "Azathothas/static-toolbox" --tag "coreutils" --asset "coreutils_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "coreutils" --asset "coreutils_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #----------#          
          ##FindUtils
          eget "Azathothas/static-toolbox" --tag "findutils" --asset "findutils_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "findutils" --asset "findutils_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #----------#          
          ##gzip
          eget "Azathothas/static-toolbox" --tag "gzip" --asset "gzip_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "gzip" --asset "gzip_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #----------#          
          ##kmod
          eget "Azathothas/static-toolbox" --tag "kmod" --asset "kmod_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "kmod" --asset "kmod_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #----------#          
          ##misc-utils
          #awk|gawk
          eget "Azathothas/static-toolbox" --tag "misc" --asset "awk_amd_x86_64" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/awk"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "awk_aarch64_arm64" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/awk"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "gawk_amd_x86_64"  --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/gawk"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "gawk_aarch64_arm64" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/gawk"
          #grep
          eget "Azathothas/static-toolbox" --tag "misc" --asset "grep_amd_x86_64" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/grep"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "grep_aarch64_arm64" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/grep"
          #sed
          eget "Azathothas/static-toolbox" --tag "misc" --asset "sed_amd_x86_64" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/sed"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "sed_aarch64_arm64" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/sed"
          #tar
          eget "Azathothas/static-toolbox" --tag "misc" --asset "tar_amd_x86_64" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/tar"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "tar_aarch64_arm64" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/tar"
          #which
          eget "Azathothas/static-toolbox" --tag "misc" --asset "which_amd_x86_64" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/which"
          eget "Azathothas/static-toolbox" --tag "misc" --asset "which_aarch64_arm64" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/which"
          #----------#
          ##OpenSSH##
          #x86_64
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "scp_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/scp"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sftp_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/sftp"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sftp_server_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/sftp-server"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-add_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/ssh-add"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-agent_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/ssh-agent"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keygen_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/ssh-keygen"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keyscan_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/ssh-keyscan"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keysign_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/ssh-keysign"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sshd_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/sshd"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sshd_config_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/sshd_config"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh_amd_x86_64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/x86_64/ssh"
          #aarch64_arm64
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "scp_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/scp"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sftp_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/sftp"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sftp_server_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/sftp-server"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-add_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/ssh-add"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-agent_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/ssh-agent"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keygen_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/ssh-keygen"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keyscan_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/ssh-keyscan"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keysign_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/ssh-keysign"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sshd_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/sshd"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sshd_config_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/sshd_config"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh_aarch64_arm64_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64/ssh"
          #armv7_eabihf
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "scp_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/scp"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sftp_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/sftp"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sftp_server_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/sftp-server"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-add_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/ssh-add"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-agent_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/ssh-agent"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keygen_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/ssh-keygen"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keyscan_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/ssh-keyscan"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh-keysign_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/ssh-keysign"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sshd_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/sshd"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "sshd_config_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/sshd_config"
          eget "Azathothas/static-toolbox" --tag "openssh" --asset "ssh_armv7_eabihf_Linux" --to "$GITHUB_WORKSPACE/main/baseutils/armv7_eabihf/ssh"          
          #----------#          
          ##procps##
          eget "Azathothas/static-toolbox" --tag "procps" --asset "procps_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "procps" --asset "procps_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #----------#
          ##util-linux
          eget "Azathothas/static-toolbox" --tag "linux" --asset "util_linux_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "linux" --asset "util_linux_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #----------#
          ##xz-utils
          eget "Azathothas/static-toolbox" --tag "xz" --asset "xz_utils_amd_x86_64" --all --to "$GITHUB_WORKSPACE/main/baseutils/x86_64"
          eget "Azathothas/static-toolbox" --tag "xz" --asset "xz_utils_aarch64_arm64" --all --to "$GITHUB_WORKSPACE/main/baseutils/aarch64_arm64"
          #-------------------------# 
          #Any leftovers
          set +x
        continue-on-error: true

     #Cleanup
      - name: Cleanup >> Strip >> chmod
        if: env.versions_same != 'true'
        run: |
          #Strip All Linux Bins
          find "$GITHUB_WORKSPACE/main/baseutils/" -type f -exec strip {} \; >/dev/null 2>&1
          #chmod +xwr everything
          find "$GITHUB_WORKSPACE/main/baseutils/" -type f -exec chmod +xwr {} \; >/dev/null 2>&1
        continue-on-error: true
        
      - name: Update README.md
        run: |
           cd "$GITHUB_WORKSPACE/main"
           touch ./baseutils/README.md
           #cat ./baseutils/INFO.md > ./baseutils/README.md
           echo -e "" >> ./baseutils/README.md 
           echo '---' >> ./baseutils/README.md
           echo '```console' >> ./baseutils/README.md
           echo -e "" >> ./baseutils/README.md
           echo -e "--> METATDATA" >> ./baseutils/README.md
           echo -e "\n[+] aarch64_arm64:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ "; file ./baseutils/aarch64_arm64/* | grep -v '.txt' ' &>> ./baseutils/README.md
           echo -e "\n[+] armv7_eabihf:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ "; file ./baseutils/armv7_eabihf/* | grep -v '.txt' ' &>> ./baseutils/README.md           
           echo -e "\n[+] x86_64:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ "; file ./baseutils/x86_64/* | grep -v '.txt' ' &>> ./baseutils/README.md
           echo -e "" >> ./baseutils/README.md
           echo -e "--> SHA256SUM" >> ./baseutils/README.md
           echo -e "\n[+] aarch64_arm64:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ ";sha256sum ./baseutils/aarch64_arm64/* | grep -v '.txt' ' &>> ./baseutils/README.md
           echo -e "\n[+] armv7_eabihf:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ ";sha256sum ./baseutils/armv7_eabihf/* | grep -v '.txt' ' &>> ./baseutils/README.md
           echo -e "\n[+] x86_64:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ ";sha256sum ./baseutils/x86_64/* | grep -v '.txt' ' &>> ./baseutils/README.md  
           echo -e '```\n' >> ./baseutils/README.md
           echo -e "" >> ./baseutils/README.md
           echo '---' >> ./baseutils/README.md
           echo -e "" >> ./baseutils/README.md
           echo '- #### Sizes' >> ./baseutils/README.md 
           echo -e "" >> ./baseutils/README.md
           echo '```console' >> ./baseutils/README.md 
           echo -e "\n[+] aarch64_arm64:\n" >> ./baseutils/README.md      
           /bin/bash -c 'PS4="$ ";ls -lh ./baseutils/aarch64_arm64/* | grep -v '.txt' | awk "{print \$5, \$9}" | column -t' &>> ./baseutils/README.md
           echo -e "\n[+] armv7_eabihf:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ ";ls -lh ./baseutils/armv7_eabihf/* | grep -v '.txt' | awk "{print \$5, \$9}" | column -t' &>> ./baseutils/README.md
           echo -e "\n[+] x86_64:\n" >> ./baseutils/README.md
           /bin/bash -c 'PS4="$ ";ls -lh ./baseutils/x86_64/* | grep -v '.txt' | awk "{print \$5, \$9}" | column -t' &>> ./baseutils/README.md
           echo '```' >> ./baseutils/README.md     
           echo -e "" >> ./baseutils/README.md 
           echo '---' >> ./baseutils/README.md 
           echo -e "" >> ./baseutils/README.md
        working-directory: main
        continue-on-error: true

      - name: Git Pull
        run: |
           cd "$GITHUB_WORKSPACE/main" && git pull origin main
        continue-on-error: true
        
      - name: Get DateTime
        run: |
          # Date Time
          NEPALI_TIME=$(TZ='Asia/Kathmandu' date +'%Y-%m-%d (%I:%M:%S %p)')
          echo "NEPALI_TIME=$NEPALI_TIME" >> $GITHUB_ENV
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "âœ… Fetch BaseUtils ðŸ“¦ <-- at ${{ env.NEPALI_TIME }} âŒš"
          #push_options: '--force'

      - name: Get Safe_DateTime
        run: |
          # Date Time
          SAFE_NEPALI_TIME=$(TZ='Asia/Kathmandu' date +'%Y-%m-%d_%I:%M:%S_%p' | tr ' :-' '_')
          echo "SAFE_NEPALI_TIME=$SAFE_NEPALI_TIME" >> $GITHUB_ENV
        continue-on-error: true

  #Create a new Release & Publish
  # Repo: https://github.com/softprops/action-gh-release
  # Market-Place: https://github.com/marketplace/actions/gh-release
      - name: Releaser
        uses: softprops/action-gh-release@v0.1.15
        with:
          name: "BaseUtils Weekly ${{ env.SAFE_NEPALI_TIME }}"
          tag_name: "baseutils_${{ env.SAFE_NEPALI_TIME }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          token: "${{ secrets.GITHUB_TOKEN }}"
          body: |
            `BaseUtils`: _https://github.com/Azathothas/Static-Binaries/tree/main/baseutils_
          files: |
            ${{github.workspace}}/main/baseutils/aarch64_arm64/*
            ${{github.workspace}}/main/baseutils/x86_64/*
